#!/sbin/busybox sh
if [ ! -f /data/LiteKernel/Backup/efsbackup.tar.gz ];
then
  mkdir -p /data/LiteKernel/Backup
  chmod 777 /data/LiteKernel/Backup
  /sbin/busybox tar zcvf /data/LiteKernel/Backup/efsbackup.tar.gz /efs
  /sbin/busybox cat /dev/block/mmcblk0p1 > /data/LiteKernel/Backup/efsdev-mmcblk0p1.img
  /sbin/busybox gzip /data/LiteKernel/Backup/efsdev-mmcblk0p1.img
  #make sure that sdcard is mounted, media scanned..etc
  (
    sleep 500
    mkdir -p /mnt/sdcard/LiteKernel
    /sbin/busybox cp /data/LiteKernel/Backup/efs* /mnt/sdcard/LiteKernel
  ) &
fi

