#!/sbin/busybox sh

busybox mount -o remount,rw /data 2>/dev/null;
busybox mount -o remount,rw /system 2>/dev/null;
busybox mount -o remount,rw `busybox mount | grep system | awk '{print $1,$3}' | sed -n 1p` 2>/dev/null;
busybox mount -o remount,ro /system 2>/dev/null;
busybox mount -o remount,ro `busybox mount | grep system | awk '{print $1,$3}' | sed -n 1p` 2>/dev/null;
if [ `cat /proc/sys/vm/dirty_background_ratio` -ne 60 ] || [ `cat /proc/sys/vm/dirty_ratio` -ne 95 ] || [ `cat /proc/sys/net/ipv4/tcp_congestion_control` != "cubic" ] || [ `cat /proc/sys/fs/lease-break-time` -ne 10 ] || [ `cat /proc/sys/vm/vfs_cache_pressure` -ne 20 ] || [ `cat /proc/sys/net/core/rmem_max` -ne 1048576 ] || [ `cat /proc/sys/net/core/optmem_max` -ne 20480 ]; then
	busybox sysctl -p;

	busybox mount -t debugfs none /sys/kernel/debug 2>/dev/null;
	echo NO_NORMALIZED_SLEEPER > /sys/kernel/debug/sched_features 2>/dev/null;
	busybox umount /sys/kernel/debug;
	
	busybox sysctl -e -w vm.min_free_kbytes=3276;
	busybox sysctl -e -w vm.oom_kill_allocating_task=0;
	busybox sysctl -e -w vm.panic_on_oom=0;
	busybox sysctl -e -w vm.dirty_background_ratio=60;
	busybox sysctl -e -w vm.dirty_ratio=95;
	busybox sysctl -e -w vm.vfs_cache_pressure=20;
	busybox sysctl -e -w vm.overcommit_memory=1;
	busybox sysctl -e -w vm.min_free_order_shift=4;
	busybox sysctl -e -w vm.laptop_mode=0;
	busybox sysctl -e -w vm.block_dump=0;
	busybox sysctl -e -w vm.oom_dump_tasks=1;
	#busybox sysctl -e -w vm.swappiness=20;
	#
	# Misc tweaks for battery life
	busybox sysctl -e -w vm.dirty_writeback_centisecs=2000;
	busybox sysctl -e -w vm.dirty_expire_centisecs=1000;
	#
	busybox sysctl -e -w kernel.panic=30;
	busybox sysctl -e -w kernel.panic_on_oops=1;
	busybox sysctl -e -w kernel.msgmni=2048;
	busybox sysctl -e -w kernel.msgmax=65536;
	busybox sysctl -e -w kernel.random.read_wakeup_threshold=128;
	busybox sysctl -e -w kernel.random.write_wakeup_threshold=256;
	busybox sysctl -e -w kernel.shmmni=4096;
	busybox sysctl -e -w kernel.shmall=2097152;
	busybox sysctl -e -w kernel.shmmax=268435456;
	busybox sysctl -e -w kernel.sem='500 512000 64 2048';
	busybox sysctl -e -w kernel.sched_features=24189;
	busybox sysctl -e -w kernel.hung_task_timeout_secs=30;             # Set to 0 to disable but can cause black screen on incoming calls
	busybox sysctl -e -w kernel.sched_latency_ns=18000000;
	busybox sysctl -e -w kernel.sched_min_granularity_ns=1500000;
	busybox sysctl -e -w kernel.sched_wakeup_granularity_ns=3000000;
	busybox sysctl -e -w kernel.sched_compat_yield=1;
	busybox sysctl -e -w kernel.sched_shares_ratelimit=256000;
	busybox sysctl -e -w kernel.sched_child_runs_first=0;
	busybox sysctl -e -w kernel.threads-max=524288;
	busybox sysctl -e -w fs.lease-break-time=10;
	busybox sysctl -e -w fs.file-max=524288;
	busybox sysctl -e -w fs.inotify.max_queued_events=32000;
	busybox sysctl -e -w fs.inotify.max_user_instances=256;
	busybox sysctl -e -w fs.inotify.max_user_watches=10240;
	  ##########################
	 #  TCP Speed & Security  #
	##########################
	# http://www.speedguide.net/articles/linux-tweaking-121
	# http://www.psc.edu/networking/projects/tcptune/#Linux
	# http://www.cyberciti.biz/faq/linux-tcp-tuning
	# http://www.cyberciti.biz/files/linux-kernel/Documentation/networking/ip-sysctl.txt
	#
	# Queue size modifications
	busybox sysctl -e -w net.core.wmem_max=1048576;
	busybox sysctl -e -w net.core.rmem_max=1048576;
	busybox sysctl -e -w net.core.rmem_default=262144;
	busybox sysctl -e -w net.core.wmem_default=262144;
	busybox sysctl -e -w net.core.optmem_max=20480;
	busybox sysctl -e -w net.unix.max_dgram_qlen=50;
	#
	busybox sysctl -e -w net.ipv4.tcp_moderate_rcvbuf=1;               # Be sure that autotuning is in effect
	busybox sysctl -e -w net.ipv4.route.flush=1;
	busybox sysctl -e -w net.ipv4.udp_rmem_min=6144;
	busybox sysctl -e -w net.ipv4.udp_wmem_min=6144;
	busybox sysctl -e -w net.ipv4.tcp_rfc1337=1;
	busybox sysctl -e -w net.ipv4.ip_no_pmtu_disc=0;
	busybox sysctl -e -w net.ipv4.tcp_ecn=0;
	busybox sysctl -e -w net.ipv4.tcp_rmem='6144 87380 1048576';
	busybox sysctl -e -w net.ipv4.tcp_wmem='6144 87380 1048576';
	busybox sysctl -e -w net.ipv4.tcp_timestamps=0;
	busybox sysctl -e -w net.ipv4.tcp_sack=1;
	busybox sysctl -e -w net.ipv4.tcp_fack=1;
	busybox sysctl -e -w net.ipv4.tcp_window_scaling=1;
	#
	# Re-use sockets in time-wait state
	busybox sysctl -e -w net.ipv4.tcp_tw_recycle=1;
	busybox sysctl -e -w net.ipv4.tcp_tw_reuse=1;
	#
	# KickAss UnderUtilized Networking Tweaks below initially suggested by avgjoemomma (from XDA)
	# Refined and tweaked by zeppelinrox... duh.
	#
	busybox sysctl -e -w net.ipv4.tcp_congestion_control=cubic;        # Change network congestion algorithm to CUBIC
	#
	# Hardening the TCP/IP stack to SYN attacks
	busybox sysctl -e -w net.ipv4.tcp_syncookies=1;
	busybox sysctl -e -w net.ipv4.tcp_synack_retries=2;
	busybox sysctl -e -w net.ipv4.tcp_syn_retries=2;
	busybox sysctl -e -w net.ipv4.tcp_max_syn_backlog=1024;
	#
	busybox sysctl -e -w net.ipv4.tcp_max_tw_buckets=16384;            # Bump up tw_buckets in case we get DoS'd
	busybox sysctl -e -w net.ipv4.icmp_echo_ignore_all=1;              # Ignore pings
	busybox sysctl -e -w net.ipv4.icmp_echo_ignore_broadcasts=1;       # Don't reply to broadcasts (prevents joining a smurf attack)
	busybox sysctl -e -w net.ipv4.icmp_ignore_bogus_error_responses=1; # Enable bad error message protection (should be enabled by default)
	busybox sysctl -e -w net.ipv4.tcp_no_metrics_save=1;               # Don't cache connection metrics from previous connection
	busybox sysctl -e -w net.ipv4.tcp_fin_timeout=15;
	busybox sysctl -e -w net.ipv4.tcp_keepalive_intvl=30;
	busybox sysctl -e -w net.ipv4.tcp_keepalive_probes=5;
	busybox sysctl -e -w net.ipv4.tcp_keepalive_time=1800;
	#
	# Don't pass traffic between networks or act as a router
	busybox sysctl -e -w net.ipv4.ip_forward=0;                        # Disable IP Packet forwarding (should be disabled already)
	busybox sysctl -e -w net.ipv4.conf.all.send_redirects=0;
	busybox sysctl -e -w net.ipv4.conf.default.send_redirects=0;
	#
	# Enable spoofing protection (turn on reverse packet filtering)
	busybox sysctl -e -w net.ipv4.conf.all.rp_filter=1;
	busybox sysctl -e -w net.ipv4.conf.default.rp_filter=1;
	#
	# Don't accept source routing
	busybox sysctl -e -w net.ipv4.conf.all.accept_source_route=0;
	busybox sysctl -e -w net.ipv4.conf.default.accept_source_route=0 ;
	#
	# Don't accept redirects
	busybox sysctl -e -w net.ipv4.conf.all.accept_redirects=0;
	busybox sysctl -e -w net.ipv4.conf.default.accept_redirects=0;
	busybox sysctl -e -w net.ipv4.conf.all.secure_redirects=0;
	busybox sysctl -e -w net.ipv4.conf.default.secure_redirects=0;
fi;
